dist: xenial
language: python
python:
  - "3.7"
cache: 
  pip: true
git:
  depth: false
  quiet: true

script:
  - python basics/hello-world.py
  - python basics/prime-numbers.py
  - python basics/prime1000.py
  - python basics/mandelbrot.py
